name: Release

permissions:
  contents: write

on: 
  push:
    tags:
      - v**


jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Electron App
        run: npm run build
      
      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "release/!(*.exe)"
      
      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          npx rimraf "release/!(*.dmg)"
      
      - name: 'Gen changelog'
        run: |
          npx changelogithub@0.12 # or changelogithub@0.12 if ensure the stable result
          ls
          cd release
          ls
  
      - name: release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/*.exe
            release/*.dmg

